
# Assignment 01: Evaluate the Ad Budget Dataset of XYZ Firm


**Happy coding!**

* * *

In [11]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


#### 1: Import the dataset

In [12]:
#Import the required libraries
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [13]:
#Import the advertising dataset
dataset = pd.read_csv('Advertising Budget and Sales.csv', index_col=0)

#### 2: Analyze the dataset

In [14]:
#View the initial few records of the dataset
dataset.head()

TV Ad Budget ($)  Radio Ad Budget ($)  Newspaper Ad Budget ($)  Sales ($)
1             230.1                 37.8                     69.2       22.1
2              44.5                 39.3                     45.1       10.4
3              17.2                 45.9                     69.3        9.3
4             151.5                 41.3                     58.5       18.5
5             180.8                 10.8                     58.4       12.9

In [15]:
#Check the total number of elements in the dataset

dataset.size

800

#### 3: Find the features or media channels used by the firm

In [16]:
#Check the number of observations (rows) and attributes (columns) in the dataset
dataset.shape

(200, 4)

In [17]:
#View the names of each of the attributes
dataset.columns

Index(['TV Ad Budget ($)', 'Radio Ad Budget ($)', 'Newspaper Ad Budget ($)',
       'Sales ($)'],
      dtype='object')

#### 4: Create objects to train and test the model; find the sales figures for each channel

In [38]:
#Create a feature object from the columns
feature_names = ['TV Ad Budget ($)', 'Radio Ad Budget ($)', 'Newspaper Ad Budget ($)']
features = dataset[feature_names]

In [39]:
#View the feature object
features

TV Ad Budget ($)  Radio Ad Budget ($)  Newspaper Ad Budget ($)
1               230.1                 37.8                     69.2
2                44.5                 39.3                     45.1
3                17.2                 45.9                     69.3
4               151.5                 41.3                     58.5
5               180.8                 10.8                     58.4
..                ...                  ...                      ...
196              38.2                  3.7                     13.8
197              94.2                  4.9                      8.1
198             177.0                  9.3                      6.4
199             283.6                 42.0                     66.2
200             232.1                  8.6                      8.7

[200 rows x 3 columns]

In [20]:
#Create a target object (Hint: use the sales column as it is the response of the dataset)
target_name = ['Sales ($)']
target = dataset[target_name]


In [21]:
#View the target object
target

Sales ($)
1         22.1
2         10.4
3          9.3
4         18.5
5         12.9
..         ...
196        7.6
197        9.7
198       12.8
199       25.5
200       13.4

[200 rows x 1 columns]

In [22]:
#Verify if all the observations have been captured in the feature object
features.shape

(200, 3)

In [23]:
#Verify if all the observations have been captured in the target object
target.shape

(200, 1)

#### 5: Split the original dataset into training and testing datasets for the model

In [24]:
#Split the dataset (by default, 75% is the training data and 25% is the testing data)
X_train, X_test, y_train, y_test = train_test_split(features, target, random_state=42)

In [25]:
#Verify if the training and testing datasets are split correctly (Hint: use the shape() method)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((150, 3), (50, 3), (150, 1), (50, 1))

#### 6: Create a model  to predict the sales outcome

In [26]:
#Create a linear regression model
linReg = LinearRegression()
linReg.fit(X_train, y_train)

LinearRegression()

In [27]:
#Print the intercept and coefficients 
print('The Intercept is : {}'.format(linReg.intercept_))
print('The Coefficient is : {}'.format(linReg.coef_))

The Intercept is : [2.77830346]
The Coefficient is : [[0.04543356 0.19145654 0.00256809]]


In [28]:
#Predict the outcome for the testing dataset
y_predicted = linReg.predict(X_test)

In [45]:
y_predicted

array([[16.38348211],
       [20.92434957],
       [21.61495426],
       [10.49069997],
       [22.17690456],
       [13.02668085],
       [21.10309295],
       [ 7.31813008],
       [13.56732111],
       [15.12238649],
       [ 8.92494113],
       [ 6.49924401],
       [14.30119928],
       [ 8.77233515],
       [ 9.58665483],
       [12.09485291],
       [ 8.59621605],
       [16.25337881],
       [10.16948105],
       [18.85753401],
       [19.5799036 ],
       [13.15877029],
       [12.25103735],
       [21.35141984],
       [ 7.69607607],
       [ 5.64686906],
       [20.79780073],
       [11.90951247],
       [ 9.06581044],
       [ 8.37295611],
       [12.40815899],
       [ 9.89416076],
       [21.42707658],
       [12.14236853],
       [18.28776857],
       [20.18114718],
       [13.99303029],
       [20.89987736],
       [10.9313953 ],
       [ 4.38721626],
       [ 9.58213448],
       [12.6170249 ],
       [ 9.93851933],
       [ 8.06816257],
       [13.45497849],
       [ 5

In [30]:
y_predicted.shape

(50, 1)

#### 7: Calculate the Mean Square Error (MSE)

In [31]:
#Import required libraries for calculating MSE (mean square error)
# --->> Imported MSE (mean square error) at the top of the NOTEBOOK

In [32]:
#Calculate the MSE
mse = np.sqrt(mean_squared_error(y_test, y_predicted))

In [33]:
mse

1.697063266379363

In [48]:
print('True Y values : ')
print(y_test.values[:10])
print('Predicted Y values : ')
print(y_predicted[:10])

True Y values : 
[[16.9]
 [22.4]
 [21.4]
 [ 7.3]
 [24.7]
 [12.6]
 [22.3]
 [ 8.4]
 [11.5]
 [14.9]]
Predicted Y values : 
[[16.38348211]
 [20.92434957]
 [21.61495426]
 [10.49069997]
 [22.17690456]
 [13.02668085]
 [21.10309295]
 [ 7.31813008]
 [13.56732111]
 [15.12238649]]
